FROM debian:buster

RUN apt-get update && apt-get install -y \
	python3 \
	python3-pip
	
RUN mkdir /code

ADD ./code-single/* /code/

RUN pip3 install -r /code/requirements.txt

CMD ["python3","/code/app.py"]