apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-nginx
data:
  index.html: "<h1>THIS IS AN ISTIO TRACING DEMO</h1>"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: configmap-landing
          mountPath: /usr/share/nginx/html/
      volumes:
        - name: configmap-landing
          configMap:
            name: landing-nginx
            items:
            - key: index.html
              path: index.html
             