apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-trace-1st-hop
  labels:
    trace: jaeger-1
spec:
  replicas: 1
  selector:
    matchLabels:
      trace: jaeger-1
  template:
    metadata:
      labels:
        trace: jaeger-1
    spec:
      containers:
      - name: jaeger-trace
        image: viejo/jaeger-trace:10
        ports:
        - containerPort: 8080
        env:
        - name: NEXT_HOP
          value: 'http://second-hop.istio-server.svc.cluster.local'
        - name: DELAY
          value: '5'